package com.inabananami.a16presentexercise;

public class ThreadDemo {
    public static void main(String[] args) {
        MyThread p1 = new MyThread();
        MyThread p2 = new MyThread();
        MyThread p3 = new MyThread();
        MyThread p4 = new MyThread();
        MyThread p5 = new MyThread();
        MyThread p6 = new MyThread();
        MyThread p7 = new MyThread();
        MyThread p8 = new MyThread();
        MyThread p9 = new MyThread();
        MyThread p10 = new MyThread();
        MyThread p11 = new MyThread();
        MyThread p12 = new MyThread();
        MyThread p13 = new MyThread();
        MyThread p14 = new MyThread();
        MyThread p15 = new MyThread();
        MyThread p16 = new MyThread();
        MyThread p17 = new MyThread();
        MyThread p18 = new MyThread();
        MyThread p19 = new MyThread();
        MyThread p20 = new MyThread();
        MyThread p21 = new MyThread();
        MyThread p22 = new MyThread();
        MyThread p23 = new MyThread();
        MyThread p24 = new MyThread();
        MyThread p25 = new MyThread();
        MyThread p26 = new MyThread();
        MyThread p27 = new MyThread();
        MyThread p28 = new MyThread();
        MyThread p29 = new MyThread();
        MyThread p30 = new MyThread();
        MyThread p31 = new MyThread();
        MyThread p32 = new MyThread();

        p1.setName("第一个人");
        p2.setName("第二个人");
        p3.setName("第三个人");
        p4.setName("第四个人");
        p5.setName("第五个人");
        p6.setName("第六个人");
        p7.setName("第七个人");
        p8.setName("第八个人");
        p9.setName("第九个人");
        p10.setName("第十个人");
        p11.setName("第十一个人");
        p12.setName("第十二个人");
        p13.setName("第十三个人");
        p14.setName("第十四个人");
        p15.setName("第十五个人");
        p16.setName("第十六个人");
        p17.setName("第十七个人");
        p18.setName("第十八个人");
        p19.setName("第十九个人");
        p20.setName("第二十个人");
        p21.setName("第二十一个人");
        p22.setName("第二十二个人");
        p23.setName("第二十三个人");
        p24.setName("第二十四个人");
        p25.setName("第二十五个人");
        p26.setName("第二十六个人");
        p27.setName("第二十七个人");
        p28.setName("第二十八个人");
        p29.setName("第二十九个人");
        p30.setName("第三十个人");
        p31.setName("第三十一个人");
        p32.setName("第三十二个人");

        p1.start();
        p2.start();
        p3.start();
        p4.start();
        p5.start();
        p6.start();
        p7.start();
        p8.start();
        p9.start();
        p10.start();
        p11.start();
        p12.start();
        p13.start();
        p14.start();
        p15.start();
        p16.start();
        p17.start();
        p18.start();
        p19.start();
        p20.start();
        p21.start();
        p22.start();
        p23.start();
        p24.start();
        p25.start();
        p26.start();
        p27.start();
        p28.start();
        p29.start();
        p30.start();
        p31.start();
        p32.start();
    }
}
